[package]
name = "pickem"
version = "0.1.0"
authors = ["Lodek <23224552+Lodek@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
