[package]
name = "pickem"
version = "0.3.0"
authors = ["Lodek <23224552+Lodek@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4"
termion = "3"
termios = "0.3"
clap = "2"
